project:
  type: book

book:
  title: "Lecture Notes in Econometrics"
  author: "Erlend Dancke Sandorf"
  date: "7/3/2024"
  chapters:
    - index.qmd
    - preface.qmd
    - part: simple-linear-regression.qmd
      chapters:
        - lecture-01.qmd
        - lecture-02.qmd
    - references.qmd
  appendices:
    - installing-r.qmd  
  page-footer:
    left: "Erlend Dancke Sandorf"
    right:
      - icon: github
      - href: https://github.com/edsandorf/lecture-notes-in-econometrics  

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual
